"""Shared visual and simulation defaults."""

from __future__ import annotations

GRASS_COLOR = "#55b64a"
GRASS_RECOVERY_START = "#587a5d"
EMPTY_COLOR = "#20352a"
GRID_COLOR = "#31543a"
HERBIVORE_COLOR = "#55c7ed"
PREDATOR_COLOR = "#ee5a55"
PANEL_COLOR = "#16221c"
TEXT_COLOR = "#eef8e9"
MUTED_COLOR = "#9db5a2"

TICK_MS = 25
RENDER_MS = 33
HISTORY_INTERVAL = 0.1
MAX_HISTORY_POINTS = 12_000

DEFAULT_HERBIVORE_STARVATION = 15.0
DEFAULT_PREDATOR_STARVATION = 12.0
DEFAULT_HERBIVORE_SPEED = 2.4
DEFAULT_PREDATOR_SPEED = 3.1

HERBIVORE_FOOD_NEEDED = 3
HERBIVORE_REPRODUCTION_WINDOW = 5.0
PREDATOR_FOOD_NEEDED = 2
PREDATOR_REPRODUCTION_WINDOW = 10.0

DEFAULT_GRASS_REGROWTH_SECONDS = 10.0
GRASS_GROWTH_STEPS = 5
GRASS_INDEPENDENT_START_CHANCE = 0.02
PREDATOR_ONLY_DELAY = 2.5
